### ISSUE TITLE
Vansah-connect Token Retrieval Issue

### ISSUE THREAD

**Issue by MerinArangassery** [testpointcorp/vansah-connect#15]
Despite successful global installation of the 'vansah-connect' npm package,
![image](https://github.com/user-attachments/assets/4ab5fe2b-3c7d-40c2-a89b-3c7ad9b2b266)
Im encountering the **following error** with retrieving the Vansah connect token, while I try to upload my results from a different directory.
![image](https://github.com/user-attachments/assets/22917618-c7a9-4b5c-aa3f-1f2b1c05790c)
This issue persists and hinders the upload process. Any guidance or troubleshooting tips would be greatly appreciated.

**Comment by ShubhamMoury** [comment]
@ShubhamMoury
[fix: load .env file from parent directory, and update token handling](https://github.com/testpointcorp/vansah-connect/pull/16/commits/cee088df1baff4166905c78c79d354024e489fc6)
